`Node.js`的多线程和多进程有什么区别？

手动实现`promise`里面，连续`resolve`两次，最后`then(arg)`里面参数的值是多少



## 实例对象与函数对象

```js
function Fn() {
  
}
const fn = new Fn(); // fn 是实例对象
console.log(Fn.prototype) //将一个函数作为对象使用时，Fn就是函数对象
Fn.call({})
//实例对象回去找原型对象上的方法
```



## 同步回调函数和异步回调函数

1. 同步回调函数

```js
const arr = [1,3,5];
arr.forEach(item => { // 遍历回调，同步回调函数，不会放入队列一上来就回执行完
  console.log(item)
})
console.log('forEach 之后')
```



2. 异步回调函数

```js
setTimeout(() => { // 异步回调函数会放入队列中，将来回执行
  console.log('timeout callback')
},0)
console.log('setTimeout 之后')
```



## js error 处理

进一步理解JS 中的

**常见错误类型**

- Error: 所有错误的父类型
- RerenceError：引用变量不存在
- TypeError：数据类型不正确错误
- RangeError：数据值不在其允许范围之内
- Styanx Error： 语法错误

**错误处理**

- 捕获错误：try ...... catch
- 抛出错误：throw error

```js
function something() {
  if(Date.now() % 2 === 0) {
    console.log('aaa')
  } else {
    throw new Error('时间是偶数')
  }
}

// 捕获异常
try {
  something();
} catch(err) {
 alert(err.message) 
}
```



**错误对象**

- message 属性
- stack 属性

常见错误类型

- ReferenceError

```js
console.log(a) //ReferenceError: a is not defined
```

- TypeError

```js
let b
b.xxx // TypeError: Cannot read property 'xxx' of undefined
```

- RangeError

```js
function fn() {
  fn();
}
fn(); // RangeError
```

- Syntax Error

```js

```





仅仅是因为一个`diff`算法和虚拟`DOM`的结合